# Generated by Django 5.2.5 on 2025-08-12 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Superhero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The superhero's name", max_length=100, unique=True
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True,
                        help_text="The superhero's real/civilian name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Alternative name or alias",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Age in years",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "powers",
                    models.TextField(
                        blank=True,
                        help_text="List of superpowers and abilities",
                        null=True,
                    ),
                ),
                (
                    "power_level",
                    models.IntegerField(
                        default=1,
                        help_text="Power level from 1 (weakest) to 10 (strongest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "origin_story",
                    models.TextField(
                        blank=True, help_text="Superhero's origin story", null=True
                    ),
                ),
                (
                    "universe",
                    models.CharField(
                        choices=[
                            ("Marvel", "Marvel Universe"),
                            ("DC", "DC Universe"),
                            ("Custom", "Custom Universe"),
                            ("Other", "Other Universe"),
                        ],
                        default="Marvel",
                        help_text="Which universe the superhero belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the superhero is currently active",
                    ),
                ),
                (
                    "is_villain",
                    models.BooleanField(
                        default=False, help_text="Whether this character is a villain"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Superhero",
                "verbose_name_plural": "Superheroes",
                "ordering": ["name"],
            },
        ),
    ]
